name: Run Non-Headless Selenium

on:
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # UPDATE: Change v3 to v6
        uses: actions/checkout@v6 

      - name: Set up Python
        # UPDATE: Change v4 to v6
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxi6 libgconf-2-4

      - name: Install Python Dependencies
        run: pip install selenium webdriver-manager

      - name: Run Selenium with Virtual Screen
        run: xvfb-run python main.py
        
      - name: Upload Screenshot
        uses: actions/upload-artifact@v6 # UPDATE: Change v4 to v6
        with:
          name: selenium-screenshot
          path: result.png
